# Generated by Django 3.1.7 on 2021-09-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exam',
            new_name='TrafficLight',
        ),
    ]
