# Generated by Django 3.1.7 on 2021-09-28 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0002_auto_20210927_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlight',
            name='duration',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='%S'),
            preserve_default=False,
        ),
    ]
