# Generated by Django 3.1.7 on 2021-09-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0003_trafficlight_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlight',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
